name: Scrape

on:
  ### Svaki dan u 8 uveče
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  Scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
        
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install requests beautifulsoup4

      - name: Execute yettel.py script
        env:
          yettel_webhook: ${{ secrets.YETTEL_WEBHOOK }}
        run: |
          python yettel.py
          
      - name: Upload changed urls.txt file
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: Dodati URL-ovi u urls.txt fajl
